// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdL8gfXz1b0NpgoEcD6tEVQ6fHwPy5fBo',
    appId: '1:654162777217:web:6feff6a3846acede66e980',
    messagingSenderId: '654162777217',
    projectId: 'eed-app',
    authDomain: 'eed-app.firebaseapp.com',
    storageBucket: 'eed-app.appspot.com',
    measurementId: 'G-5PM9K7J6K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZWsgOYmIKv-1Uk57F4Tow4Ebi5iaO_Tw',
    appId: '1:654162777217:android:a3a785f5cc630c4f66e980',
    messagingSenderId: '654162777217',
    projectId: 'eed-app',
    storageBucket: 'eed-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8SBg4A0KjYU-LxnR1z6Gobk0XNg6fS1E',
    appId: '1:654162777217:ios:7cdecef4ed42f17866e980',
    messagingSenderId: '654162777217',
    projectId: 'eed-app',
    storageBucket: 'eed-app.appspot.com',
    iosBundleId: 'com.example.roomFinderFlutter',
  );

}